Document new changes
Kristify/kristify.github.io pull request #3
Opened 2023-06-13 15:46 UTC by slimit75

This was an attempt to document changes to the config that I am making in a separate pull request to [Kristify](https://github.com/Kristify/Kristify) and therefore won't be ready until that pull request is done. The full changes are below:

- [x] Document new options
- [x] Fix typos & table formatting that my IDE was complaining about
- [x] Add new options to configgen

2023-06-14 16:22 UTC, piprett approved these changes
A lot of great work here, and thanks for fixing all the typos! Ill test the new code added more in-depth later, but I am happy with all the markdowns!

2023-06-15 15:41 UTC, piprett requested changes
It appears that the "broadcastLocation" option is required to be specified, even if ShopSync is disabled. I've pointed it out in some specific review comments, along with a fix.

2023-06-15 15:41 UTC, piprett commented on docs/configgen/script.js
> +      broadcastLocation = ${this.ssLocEnabled},
```suggestion
      broadcastLocation = ${this.ssLocEnabled || 'false'},
```

2023-06-15 15:41 UTC, piprett commented on docs/configgen/index.html
> +                <select id="ssLocEnabled" class="form-select" v-model="ssLocEnabled" required>
```suggestion
                <select id="ssLocEnabled" class="form-select" v-model="ssLocEnabled">
```

2023-06-15 16:07 UTC, slimit75 commented
My bad, should be fixed now

2023-06-15 16:08 UTC, piprett approved these changes

2023-06-15 16:09 UTC, merged